<a href="https://colab.research.google.com/github/Shrez7961/Practice/blob/main/Assignment_NumPy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <u> Use only those concepts which have been taught till now </u>

In [1]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [2]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [3]:
# Your code here
slice_array = random_integers[:5,3:]
slice_array


array([[140037,  81969],
       [481981, 176739],
       [394863,  25024],
       [485118,  16119],
       [109413, 103399]])

In [4]:
#Average of individual list in slice
for i in range(5):
  avg =slice_array[i].sum()/slice_array[i].size
  print(avg)


111003.0
329360.0
209943.5
250618.5
106406.0


In [5]:
#Average of total slice
avrg=slice_array.sum()/slice_array.size
avrg

201466.2

#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [6]:
# Create the 10 points
np.random.seed(21)
d2arr = np.random.randint(5,20,10).reshape(2,5)
d2arr

array([[14, 13,  9,  5,  5],
       [13,  8, 17,  7,  6]])

In [7]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair
A=[]
B=[]
for i in d2arr:
  for j in i:
    for k in range(len(i)):
      a = (j,i[k])
      b = (j,i[k])
      A.append(a)
      B.append(b)

print(A)
print(B)

[(14, 14), (14, 13), (14, 9), (14, 5), (14, 5), (13, 14), (13, 13), (13, 9), (13, 5), (13, 5), (9, 14), (9, 13), (9, 9), (9, 5), (9, 5), (5, 14), (5, 13), (5, 9), (5, 5), (5, 5), (5, 14), (5, 13), (5, 9), (5, 5), (5, 5), (13, 13), (13, 8), (13, 17), (13, 7), (13, 6), (8, 13), (8, 8), (8, 17), (8, 7), (8, 6), (17, 13), (17, 8), (17, 17), (17, 7), (17, 6), (7, 13), (7, 8), (7, 17), (7, 7), (7, 6), (6, 13), (6, 8), (6, 17), (6, 7), (6, 6)]
[(14, 14), (14, 13), (14, 9), (14, 5), (14, 5), (13, 14), (13, 13), (13, 9), (13, 5), (13, 5), (9, 14), (9, 13), (9, 9), (9, 5), (9, 5), (5, 14), (5, 13), (5, 9), (5, 5), (5, 5), (5, 14), (5, 13), (5, 9), (5, 5), (5, 5), (13, 13), (13, 8), (13, 17), (13, 7), (13, 6), (8, 13), (8, 8), (8, 17), (8, 7), (8, 6), (17, 13), (17, 8), (17, 17), (17, 7), (17, 6), (7, 13), (7, 8), (7, 17), (7, 7), (7, 6), (6, 13), (6, 8), (6, 17), (6, 7), (6, 6)]


In [ ]:
for m in A:
    for n in B:
      ED= ((m[0]-m[1])**2 +(n[0]-n[1])**2)**(0.5)
      print(int(ED))

In [ ]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.

for m in A:
    for n in B:
      MD= (np.absolute(m[0]-m[1]) +np.absolute(n[0]-n[1]))
      print((MD))



## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [10]:
# Your code here





# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [19]:
# Your code below ..
np.random.seed(21)
matrix = np.random.randint(1,9,size=(10,10))
matrix


array([[2, 8, 1, 5, 1, 1, 1, 4, 5, 3],
       [8, 2, 3, 1, 7, 8, 5, 6, 6, 2],
       [6, 7, 3, 1, 7, 5, 7, 5, 4, 5],
       [8, 5, 1, 2, 6, 7, 6, 3, 7, 3],
       [1, 5, 3, 1, 6, 6, 1, 3, 4, 1],
       [1, 4, 2, 5, 1, 3, 8, 7, 5, 3],
       [5, 2, 1, 6, 1, 6, 6, 4, 2, 7],
       [4, 5, 5, 7, 7, 5, 7, 2, 1, 3],
       [3, 3, 1, 1, 8, 2, 8, 6, 7, 3],
       [2, 8, 2, 1, 3, 3, 8, 7, 1, 2]])

In [24]:
matrix[:3,:3]

array([[2, 8, 1],
       [8, 2, 3],
       [6, 7, 3]])

In [29]:
len(matrix)

10

In [33]:
for j in range(len(matrix)-2):
    for i in range(len(matrix)-2):
      print(matrix[j:j+3,i:i+3])

[[2 8 1]
 [8 2 3]
 [6 7 3]]
[[8 1 5]
 [2 3 1]
 [7 3 1]]
[[1 5 1]
 [3 1 7]
 [3 1 7]]
[[5 1 1]
 [1 7 8]
 [1 7 5]]
[[1 1 1]
 [7 8 5]
 [7 5 7]]
[[1 1 4]
 [8 5 6]
 [5 7 5]]
[[1 4 5]
 [5 6 6]
 [7 5 4]]
[[4 5 3]
 [6 6 2]
 [5 4 5]]
[[8 2 3]
 [6 7 3]
 [8 5 1]]
[[2 3 1]
 [7 3 1]
 [5 1 2]]
[[3 1 7]
 [3 1 7]
 [1 2 6]]
[[1 7 8]
 [1 7 5]
 [2 6 7]]
[[7 8 5]
 [7 5 7]
 [6 7 6]]
[[8 5 6]
 [5 7 5]
 [7 6 3]]
[[5 6 6]
 [7 5 4]
 [6 3 7]]
[[6 6 2]
 [5 4 5]
 [3 7 3]]
[[6 7 3]
 [8 5 1]
 [1 5 3]]
[[7 3 1]
 [5 1 2]
 [5 3 1]]
[[3 1 7]
 [1 2 6]
 [3 1 6]]
[[1 7 5]
 [2 6 7]
 [1 6 6]]
[[7 5 7]
 [6 7 6]
 [6 6 1]]
[[5 7 5]
 [7 6 3]
 [6 1 3]]
[[7 5 4]
 [6 3 7]
 [1 3 4]]
[[5 4 5]
 [3 7 3]
 [3 4 1]]
[[8 5 1]
 [1 5 3]
 [1 4 2]]
[[5 1 2]
 [5 3 1]
 [4 2 5]]
[[1 2 6]
 [3 1 6]
 [2 5 1]]
[[2 6 7]
 [1 6 6]
 [5 1 3]]
[[6 7 6]
 [6 6 1]
 [1 3 8]]
[[7 6 3]
 [6 1 3]
 [3 8 7]]
[[6 3 7]
 [1 3 4]
 [8 7 5]]
[[3 7 3]
 [3 4 1]
 [7 5 3]]
[[1 5 3]
 [1 4 2]
 [5 2 1]]
[[5 3 1]
 [4 2 5]
 [2 1 6]]
[[3 1 6]
 [2 5 1]
 [1 6 1]]
[[1 6 6]
 [5 1 3]
 [

#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [172]:
# Your function below
#Creating a random array
array_random = np.random.randint(10,500,15)
array_random


array([194, 168, 472,  11, 344, 203,  46, 128, 260, 386, 455, 191, 394,
       269, 273])

In [173]:
#Defining a function for calling nearest number from array
def nearest_point(random_array):
  element=int(input("Enter Your Number:\n"))
  
  #Creating a list for numbers less than input number(element)
  lst1=[]
  for i in random_array:
    if i < element:
      lst1.append(i)

  #Get nearest number from inputted number in  lst1
  if len(lst1)>0:
    maxi=max(lst1)

  #Creating a list for numbers greater than input number(element)
  lst2=[]
  for i in random_array:
    if i > element:
      lst2.append(i)

  #Get nearest number from inputted number in  lst2    
  if len(lst2)>0:
    mini=min(lst2)

  #Checking all the conditionals to get the nearest number
  if len(lst1)==0:
    print(f"The nearest point of {element} is {mini}")

  elif len(lst2)==0:
    print(f"The nearest point of {element} is {maxi}")

  elif (element-maxi) == (mini-element):
    print((f"The nearest point of {element} are {maxi} and {mini}"))

  elif (element-maxi) < (mini-element):
    print(f"The nearest point of {element} is {maxi}")
    
  elif(element-maxi) > (mini-element):
    print(f"The nearest point of  {element} is {mini}")

In [175]:
nearest_point(array_random)

Enter Your Number:
10
The nearest point of 10 is 11
